### ISSUE TITLE
How to configure DNS server on Windows pod?

### ISSUE THREAD

**Issue by ylhyh** [openvswitch/ovn-kubernetes#655]
I'm facing a DNS issue on Windows pod, DNS servers on Windows pod are setting to [ fec0:0:0:ffff::1%1, fec0:0:0:ffff::3%1, and fec0:0:0:ffff::3%1 ] by default:
```
C:\>ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : rtx-service-6cbd744ddf-vf26b
   Primary Dns Suffix  . . . . . . . : 
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter vEthernet (default_rtx-service-6cbd744ddf-vf26b):

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #4
   Physical Address. . . . . . . . . : 0A-00-00-00-01-74
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::f5a7:5bb9:1351:3ead%19(Preferred) 
   IPv4 Address. . . . . . . . . . . : 10.112.11.3(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.112.11.1
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Disabled
```
it doesn't work with the default DNS server when lookup a domain:
```
C:\>nslookup www.google.com           
Server:  UnKnown
Address:  fec0:0:0:ffff::1

*** UnKnown can't find www.google.com: No response from server
```

If I specify the DNS server, nslookup work properly:
```
C:\>nslookup www.google.com 10.96.0.10
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.96.0.10

Non-authoritative answer:
Name:    www.google.com
Addresses:  2404:6800:4005:811::2004
	  199.59.150.11
```

CNI configuration is generates by ovnkube.exe, the "dns" section is empty:
```
{
    "cniVersion": "0.3.1",
    "name": "ovn-kubernetes",
    "type": "ovn-k8s-cni-overlay.exe",
    "ipam": {},
    "dns": {}
}
```

I have tried to configure "dns" section manualy and it is still not work:
```
{
    "cniVersion": "0.3.1",
    "name": "ovn-kubernetes",
    "type": "ovn-k8s-cni-overlay.exe",
    "ipam": {},
    "dns": {
        "servers": [
            "10.96.0.10"
        ],
        "searches": [
            "default.svc.cluster.local",
            "svc.cluster.local",
            "cluster.local",
            "q1lan.k8s"
        ],
        "options": []
    }
}
```
And the "dns" section will be cleared after ovnkube restart.

**Component Version:**
- Windows Version:  Windows Server Core 1709 (10.0.16299.125)
- Docker Version: 18.09.3
- ovn-kubernetes git hash: 378afe237ff8e9877714ee664cee2fdcb5bbfc58
- Kubernetes: v1.13.3

HNS Endpoint on Windows Minion Node:
```
PS D:\k8s\cni\net.d> Get-HnsEndpoint


ActivityId                : 71f895fe-ac23-40e9-8692-c6fe3a153790
CreateProcessingStartTime : 131979873594810828
GatewayAddress            : 10.112.11.1
ID                        : 31778de6-aece-461c-ad74-5a1e2389cd46
IPAddress                 : 10.112.11.3
MacAddress                : 0a-00-00-00-01-74
Name                      : default_rtx-service-6cbd744ddf-vf26b
Policies                  : {}
PrefixLength              : 24
Resources                 : @{AllocationOrder=2; Allocators=System.Object[]; ID=71f895fe-ac23-40e9-8692-c6fe3a153790; PortOperationTime=0; State=1; SwitchOperationTime=0; VfpOperationTime=0; parentId=f148b3bb
                            -a7de-4c11-b638-ec677de0a2c0}
SharedContainers          : {}
StartTime                 : 131979873603431110
State                     : 3
Type                      : Transparent
Version                   : 21474836481
VirtualNetwork            : c3bdff7e-bd77-436b-91ce-557f28940b11
VirtualNetworkName        : HNSTransparent
```

Kubelet config.yaml:
```
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: D:/k8s/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
cgroupsPerQOS: false
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
configMapAndSecretChangeDetectionStrategy: Watch
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuCFSQuotaPeriod: 100ms
cpuManagerPolicy: none
cpuManagerReconcilePeriod: 10s
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enforceNodeAllocatable: []
eventBurst: 10
eventRecordQPS: 5
evictionHard:
  imagefs.available: 15%
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: true
fileCheckFrequency: 20s
hairpinMode: promiscuous-bridge
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 20s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kind: KubeletConfiguration
kubeAPIBurst: 10
kubeAPIQPS: 5
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 110
nodeLeaseDurationSeconds: 40
nodeStatusReportFrequency: 1m0s
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: -1
port: 10250
registryBurst: 10
registryPullQPS: 5
resolvConf: D:/k8s/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 2m0s
serializeImagePulls: true
staticPodPath: D:/k8s/pods
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
volumeStatsAggPeriod: 1m0s
```

- [Kubelet Log](https://gist.githubusercontent.com/ylhyh/19b50cc0773545cadbf6cd0702d0583e/raw/8076ec93beb85af5c2462fa5d3b55d54282d9e45/kubelet.log)
- [ovnkube log](https://gist.github.com/ylhyh/19b50cc0773545cadbf6cd0702d0583e/raw/8076ec93beb85af5c2462fa5d3b55d54282d9e45/ovn-kubernetes.log)
