### ISSUE TITLE
Bug: reference pod targetPort by name doesn't work

### ISSUE THREAD

**Issue by pires** [openvswitch/ovn-kubernetes#80]
Having the following descriptors...

`iis-pod.yaml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: iis
  labels:
    component: iis-http-server
spec:
  containers:
  - name: iis
    image: microsoft/iis:nanoserver
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: iis-http
  nodeSelector:
    beta.kubernetes.io/os: windows
```

`iis-svc.yaml`:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: iis
spec:
  clusterIP: 10.100.28.123
  selector:
    component: iis-http-server
  ports:
  - name: http
    port: 80
    targetPort: iis-http
```

...works in Kubernetes because the controller-manager block that takes care of service endpoints can map service `targetPort: iis-http` to pod `containerPort: 80` (mapped by `name: iis-http`).

However, OVN doesn't follow:
```
$ sudo ovn-nbctl list Load_Balancer
_uuid               : a53b0274-aeb9-4ec0-9668-acbb09077297
external_ids        : {"k8s-cluster-lb-tcp"=yes}
protocol            : []
vips                : {"10.100.0.10:53"="172.17.0.2:53", "10.100.0.1:443"="10.142.0.2:443", "10.100.28.123:80"="10.244.5.234:iis-http"}

_uuid               : 99f881dd-b0cf-492e-8008-2cc1be371829
external_ids        : {"k8s-cluster-lb-udp"=yes}
protocol            : udp
vips                : {"10.100.0.10:53"="172.17.0.2:53"}
```

The issue is `"10.244.5.234:iis-http"`.
